version: "3.9"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  db_pma:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8082:80"
    volumes:
     - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_USER: root
#  mail:
#    image: mailhog/mailhog:latest
#    ports:
#      - "8081:8025"
#   www:
#     depends_on:
#       - db
#       - mail
#     image: php:apache
#     volumes:
#       - www:/var/www/html
#     ports:
#       - "8080:80"

volumes:
  mysql-data:
